---
- name: Ensure SDDM configuration is in place
  lineinfile:
    path: /etc/sddm.conf
    regex: "#ServerArguments"
    line: "ServerArguments=-nolisten tcp -background none"

- name: Ensure SDDM configuration is in place
  lineinfile:
    path: /etc/sddm.conf
    regex: "Current="
    line: "Current=Sweet"

- name: Add custom wayland-session to load Sweet theme prior to display
  copy:
    src: files/wayland-session.sh
    dest: /etc/sddm/wayland-session
    mode: '0755'

- name: Stop / disable the lightdm service
  ansible.builtin.systemd:
    name: lightdm
    enabled: false
    state: stopped

- name: Start / enable the SDDM service
  ansible.builtin.systemd:
    state: started
    name: sddm
    enabled: true
