---
- name: Apply theme gsettings
  include_tasks: misc/gsetting.yml
  loop: '{{ gsetting_configs }}'

- name: Apply xfconf settings
  community.general.system.xfconf:
    channel: '{{ item.channel }}'
    property: '{{ item.property }}'
    value_type: "{{ item.value_type | default('string') }}"
    value: '{{ item.value }}'
  failed_when: false
  loop: '{{ xconf_settings }}'
