---
- name: update grub
  become: true
  shell:
    cmd: |
      if [ -d /sys/firmware/efi ]; then
        grub2-mkconfig -o /boot/efi/EFI/qubes/grub.cfg
      else
        grub2-mkconfig -o /boot/grub2/grub.cfg
      fi
  args:
    executable: /bin/bash

- name: update initramfs
  become: true
  shell: dracut -f
